name: movemate_staff
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.0.15
  dotted_border: ^2.1.0
  carousel_slider: ^4.0.0
  image_picker: ^1.1.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Router
  auto_route: ^7.8.4

  # Handle exception
  fpdart: ^1.1.0

  # Networking
  retrofit: ^4.0.3
  dio: ^5.4.0
  awesome_dio_interceptor:
    ^1.0.0

    # Firebase
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  firebase_auth:
    ^4.0.0

    #Icon
  icons_plus:
    ^4.0.0

    # Order
  photo_view:
    ^0.14.0

    # Animation
  lottie: ^2.7.0
  flag: ^7.0.0
  font_awesome_flutter: ^10.6.0
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  timeline_tile: ^2.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  retrofit_generator: ^8.0.4
  riverpod_generator: ^2.3.6
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  plugin_platform_interface: ^2.1.7
  freezed: ^2.5.7
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/background/
    - assets/images/booking/
    - assets/images/home/
    - assets/images/logo_wallets/
    - assets/images/onboarding/
    - assets/images/profile/
    - assets/images/promotion/
    - assets/images/splash/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
