// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmTzwsa9AYKit0984cHmSR4xGLkmuKA9U',
    appId: '1:739539035350:web:1559840d705631a508d577',
    messagingSenderId: '739539035350',
    projectId: 'movemate-firebase',
    authDomain: 'movemate-firebase.firebaseapp.com',
    storageBucket: 'movemate-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClEBLwLjSXE9N3e4eaa0VmqfAk0PxomMw',
    appId: '1:739539035350:android:b47131be51a511d708d577',
    messagingSenderId: '739539035350',
    projectId: 'movemate-firebase',
    storageBucket: 'movemate-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGsA_TFLZkjI4LbI494mgnN1JIyJ3vtNE',
    appId: '1:739539035350:ios:4c80504db8033eec08d577',
    messagingSenderId: '739539035350',
    projectId: 'movemate-firebase',
    storageBucket: 'movemate-firebase.appspot.com',
    iosBundleId: 'com.example.movemateStaff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGsA_TFLZkjI4LbI494mgnN1JIyJ3vtNE',
    appId: '1:739539035350:ios:4c80504db8033eec08d577',
    messagingSenderId: '739539035350',
    projectId: 'movemate-firebase',
    storageBucket: 'movemate-firebase.appspot.com',
    iosBundleId: 'com.example.movemateStaff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmTzwsa9AYKit0984cHmSR4xGLkmuKA9U',
    appId: '1:739539035350:web:c3cfc8a980038d0108d577',
    messagingSenderId: '739539035350',
    projectId: 'movemate-firebase',
    authDomain: 'movemate-firebase.firebaseapp.com',
    storageBucket: 'movemate-firebase.appspot.com',
  );
}
